# Generated by Django 5.2.5 on 2025-08-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "year_of_passing",
                    models.CharField(
                        choices=[("2026", "2026"), ("2027", "2027"), ("2028", "2028")],
                        max_length=4,
                    ),
                ),
                ("college_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100, unique=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            (
                                "Speculative / Future Design",
                                "Speculative / Future Design",
                            ),
                            (
                                "Immersive Interaction Design (AR/VR/XR)",
                                "Immersive Interaction Design (AR/VR/XR)",
                            ),
                            ("AI in Education", "AI in Education"),
                            ("AI in Agriculture", "AI in Agriculture"),
                            ("AI in Healthcare", "AI in Healthcare"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "idea_submission_pdf",
                    models.FileField(upload_to="idea_submissions/"),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_team",
                        to="registration.participant",
                    ),
                ),
                (
                    "participant_2",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_participant_2",
                        to="registration.participant",
                    ),
                ),
                (
                    "participant_3",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_participant_3",
                        to="registration.participant",
                    ),
                ),
                (
                    "participant_4",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_participant_4",
                        to="registration.participant",
                    ),
                ),
            ],
        ),
    ]
