# Generated by Django 5.2.5 on 2025-08-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="participant_2",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_participant_2",
                to="registration.participant",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="participant_3",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_participant_3",
                to="registration.participant",
            ),
        ),
    ]
