# Generated by Django 5.2.5 on 2025-08-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_team_participant_2_alter_team_participant_3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="qr_code",
        ),
    ]
